### PR TITLE
Feature/158978968/error box fixes

### PR DESCRIPTION
**Pull request by jkoulish-bixal**
See #246 for details.......everything is the same plus a couple alignment tweaks I worked through with Phil.

## New Screenshots as Phil-approved

screen shot 2018-08-02 at 3 45 11 pm

screen shot 2018-08-02 at 3 45 55 pm

screen shot 2018-08-02 at 3 46 13 pm

### CODE REVIEW

**Comment by ivonne-gov** [comment]
I can see that you pulled in the latest changes, but for some reason this file still exists in the PR:
web/modules/custom/react_tools/tools/build/static/js/react-locator-map.min.js

**Comment by jkoulish-bixal** [comment]
Ugh I thought I'd gotten the build files removed. I'll delete the applicable build folder, make sure it registers in git, and push again. Hopefully a new PR isn't necessary....

**Comment by jkoulish-bixal** [comment]
Ok @ivonne-gov PR is updated with that file stripped out. Should be good to go now (once CircleCI is finished doing its thing).....

**Comment by ivonne-gov** [comment]
screen shot 2018-08-07 at 1 02 30 pm

**Comment by ivonne-gov** [comment]
nevermind I was looking at the testing at #246. It is working as it is specified in this updated PR.

**Pull request merged**
